#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Codex
##
##############################################################################

APP_BASE_NAME=`basename "$0"`
APP_HOME=`cd "$(dirname "$0")" >/dev/null && pwd`

default_jvm_opts="-Xmx64m -Xms64m"

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
  echo "Gradle wrapper JAR missing. Run 'gradle wrapper' or open the project in Android Studio to regenerate it." >&2
  exit 1
fi

exec "$JAVA_HOME/bin/java" ${JAVA_OPTS} ${GRADLE_OPTS} -Dorg.gradle.appname=$APP_BASE_NAME \
  -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
